#!/bin/bash


_get_repolink () {
    local regex
    regex='(https?)://github.com/.+/.+'
    if [[ $CMSBOT_REPO == "CMSBOT" ]]
    then
        echo "aHR0cHM6Ly9naXRodWIuY29tL1Jlbmdva3VzYW4wMDEvQ01TVVNFUkJPVFVTRVJCT1QvYXJjaGl2ZS9tYXN0ZXIuemlw" | base64 -d
    elif [[ $CMSBOT_REPO == "CMSBOT" ]]
    then
        echo "aHR0cHM6Ly9naXRodWIuY29tL1Jlbmdva3VzYW4wMDEvQ01TVVNFUkJPVFVTRVJCT1QvYXJjaGl2ZS9tYXN0ZXIuemlw" | base64 -d
    elif [[ $CMSBOT_REPO =~ $regex ]]
    then
        if [[ $CMSBOT_REPO_BRANCH ]]
        then
            echo "${CMSBOT_REPO}/archive/${CMSBOT_REPO_BRANCH}.zip"
        else
            echo "${CMSBOT_REPO}/archive/master.zip"
        fi
    else
        echo "aHR0cHM6Ly9naXRodWIuY29tL1Jlbmdva3VzYW4wMDEvQ01TVVNFUkJPVFVTRVJCT1QvYXJjaGl2ZS9tYXN0ZXIuemlw" | base64 -d
    fi
}


_set_bot () {
    local zippath
    zippath="CMSBOT.zip"
    echo "  ⚜Starting Downloading CMSBOT Source Code...❤"
    wget -q $(_get_repolink) -O "$zippath"
    echo "  Unpacking Data ..."
    CMSBOTPATH=$(zipinfo -1 "$zippath" | grep -v "/.");
    unzip -qq "$zippath"
    echo "Done"
    echo "  CMSBOT Cleaning.."
    rm -rf "$zippath"
    sleep 5
    cd $CMSBOTPATH
    echo "    • Starting CMSBOT •    "
    echo "
    CMSBOT
    "

    python3 ../setup/updater.py ../requirements.txt requirements.txt
    python3 -m userbot
}

_set_bot
